// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"

	"github.com/actgardner/gogen-avro/vm/types"
	"github.com/actgardner/gogen-avro/vm"
)

func writeArrayDiaForcedSource(r []*DiaForcedSource, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)),w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeDiaForcedSource(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0,w)
}



type ArrayDiaForcedSourceWrapper []*DiaForcedSource

func (_ *ArrayDiaForcedSourceWrapper) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *ArrayDiaForcedSourceWrapper) SetInt(v int32) { panic("Unsupported operation") }
func (_ *ArrayDiaForcedSourceWrapper) SetLong(v int64) { panic("Unsupported operation") }
func (_ *ArrayDiaForcedSourceWrapper) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *ArrayDiaForcedSourceWrapper) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *ArrayDiaForcedSourceWrapper) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *ArrayDiaForcedSourceWrapper) SetString(v string) { panic("Unsupported operation") }
func (_ *ArrayDiaForcedSourceWrapper) SetUnionElem(v int64) { panic("Unsupported operation") }
func (_ *ArrayDiaForcedSourceWrapper) Get(i int) types.Field { panic("Unsupported operation") }
func (_ *ArrayDiaForcedSourceWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *ArrayDiaForcedSourceWrapper) Finalize() { }
func (_ *ArrayDiaForcedSourceWrapper) SetDefault(i int) { panic("Unsupported operation") }
func (r *ArrayDiaForcedSourceWrapper) AppendArray() types.Field {
	var v *DiaForcedSource
	
	v = NewDiaForcedSource()

 	
	*r = append(*r, v)
        
        return (*r)[len(*r)-1]
        
}
