// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"github.com/actgardner/gogen-avro/vm/types"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/compiler"
)


type Pm_parallax_Cov struct {

	
	
		PmRaSigma float32
	

	
	
		PmDeclSigma float32
	

	
	
		ParallaxSigma float32
	

	
	
		PmRa_pmDecl_Cov float32
	

	
	
		PmRa_parallax_Cov float32
	

	
	
		PmDecl_parallax_Cov float32
	

}

const Pm_parallax_CovAvroCRC64Fingerprint = "\xeb\xb4\x17i\xd2&$P"

func NewPm_parallax_Cov() (*Pm_parallax_Cov) {
	return &Pm_parallax_Cov{}
}

func DeserializePm_parallax_Cov(r io.Reader) (*Pm_parallax_Cov, error) {
	t := NewPm_parallax_Cov()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err
	}
	return t, err
}

func DeserializePm_parallax_CovFromSchema(r io.Reader, schema string) (*Pm_parallax_Cov, error) {
	t := NewPm_parallax_Cov()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err
	}
	return t, err
}

func writePm_parallax_Cov(r *Pm_parallax_Cov, w io.Writer) error {
	var err error
	
	err = vm.WriteFloat( r.PmRaSigma, w)
	if err != nil {
		return err
	}
	
	err = vm.WriteFloat( r.PmDeclSigma, w)
	if err != nil {
		return err
	}
	
	err = vm.WriteFloat( r.ParallaxSigma, w)
	if err != nil {
		return err
	}
	
	err = vm.WriteFloat( r.PmRa_pmDecl_Cov, w)
	if err != nil {
		return err
	}
	
	err = vm.WriteFloat( r.PmRa_parallax_Cov, w)
	if err != nil {
		return err
	}
	
	err = vm.WriteFloat( r.PmDecl_parallax_Cov, w)
	if err != nil {
		return err
	}
	
	return err
}

func (r *Pm_parallax_Cov) Serialize(w io.Writer) error {
	return writePm_parallax_Cov(r, w)
}

func (r *Pm_parallax_Cov) Schema() string {
	return "{\"fields\":[{\"name\":\"pmRaSigma\",\"type\":\"float\"},{\"name\":\"pmDeclSigma\",\"type\":\"float\"},{\"name\":\"parallaxSigma\",\"type\":\"float\"},{\"name\":\"pmRa_pmDecl_Cov\",\"type\":\"float\"},{\"name\":\"pmRa_parallax_Cov\",\"type\":\"float\"},{\"name\":\"pmDecl_parallax_Cov\",\"type\":\"float\"}],\"name\":\"lsst.pm_parallax_Cov\",\"type\":\"record\"}"
}

func (r *Pm_parallax_Cov) SchemaName() string {
	return "lsst.pm_parallax_Cov"
}

func (_ *Pm_parallax_Cov) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Pm_parallax_Cov) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Pm_parallax_Cov) SetLong(v int64) { panic("Unsupported operation") }
func (_ *Pm_parallax_Cov) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Pm_parallax_Cov) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Pm_parallax_Cov) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Pm_parallax_Cov) SetString(v string) { panic("Unsupported operation") }
func (_ *Pm_parallax_Cov) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *Pm_parallax_Cov) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
			return (*types.Float)(&r.PmRaSigma)
		
	
	case 1:
		
		
			return (*types.Float)(&r.PmDeclSigma)
		
	
	case 2:
		
		
			return (*types.Float)(&r.ParallaxSigma)
		
	
	case 3:
		
		
			return (*types.Float)(&r.PmRa_pmDecl_Cov)
		
	
	case 4:
		
		
			return (*types.Float)(&r.PmRa_parallax_Cov)
		
	
	case 5:
		
		
			return (*types.Float)(&r.PmDecl_parallax_Cov)
		
	
	}
	panic("Unknown field index")
}

func (r *Pm_parallax_Cov) SetDefault(i int) {
	switch (i) {
	
        
	
        
	
        
	
        
	
        
	
        
	
	}
	panic("Unknown field index")
}

func (_ *Pm_parallax_Cov) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Pm_parallax_Cov) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Pm_parallax_Cov) Finalize() { }


func (_ *Pm_parallax_Cov) AvroCRC64Fingerprint() []byte {
  return []byte(Pm_parallax_CovAvroCRC64Fingerprint)
}
