// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"github.com/actgardner/gogen-avro/vm/types"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/compiler"
)


type Ps_Cov struct {

	
	
		PsFluxSigma float32
	

	
	
		PsRaSigma float32
	

	
	
		PsDeclSigma float32
	

	
	
		PsFlux_psRa_Cov float32
	

	
	
		PsFlux_psDecl_Cov float32
	

	
	
		PsRa_psDecl_Cov float32
	

}

const Ps_CovAvroCRC64Fingerprint = "\xee\xc8r\x88\xfb5\x1c\xdd"

func NewPs_Cov() (*Ps_Cov) {
	return &Ps_Cov{}
}

func DeserializePs_Cov(r io.Reader) (*Ps_Cov, error) {
	t := NewPs_Cov()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err
	}
	return t, err
}

func DeserializePs_CovFromSchema(r io.Reader, schema string) (*Ps_Cov, error) {
	t := NewPs_Cov()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err
	}
	return t, err
}

func writePs_Cov(r *Ps_Cov, w io.Writer) error {
	var err error
	
	err = vm.WriteFloat( r.PsFluxSigma, w)
	if err != nil {
		return err
	}
	
	err = vm.WriteFloat( r.PsRaSigma, w)
	if err != nil {
		return err
	}
	
	err = vm.WriteFloat( r.PsDeclSigma, w)
	if err != nil {
		return err
	}
	
	err = vm.WriteFloat( r.PsFlux_psRa_Cov, w)
	if err != nil {
		return err
	}
	
	err = vm.WriteFloat( r.PsFlux_psDecl_Cov, w)
	if err != nil {
		return err
	}
	
	err = vm.WriteFloat( r.PsRa_psDecl_Cov, w)
	if err != nil {
		return err
	}
	
	return err
}

func (r *Ps_Cov) Serialize(w io.Writer) error {
	return writePs_Cov(r, w)
}

func (r *Ps_Cov) Schema() string {
	return "{\"fields\":[{\"name\":\"psFluxSigma\",\"type\":\"float\"},{\"name\":\"psRaSigma\",\"type\":\"float\"},{\"name\":\"psDeclSigma\",\"type\":\"float\"},{\"name\":\"psFlux_psRa_Cov\",\"type\":\"float\"},{\"name\":\"psFlux_psDecl_Cov\",\"type\":\"float\"},{\"name\":\"psRa_psDecl_Cov\",\"type\":\"float\"}],\"name\":\"lsst.alert.ps_Cov\",\"type\":\"record\"}"
}

func (r *Ps_Cov) SchemaName() string {
	return "lsst.alert.ps_Cov"
}

func (_ *Ps_Cov) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Ps_Cov) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Ps_Cov) SetLong(v int64) { panic("Unsupported operation") }
func (_ *Ps_Cov) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Ps_Cov) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Ps_Cov) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Ps_Cov) SetString(v string) { panic("Unsupported operation") }
func (_ *Ps_Cov) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *Ps_Cov) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
			return (*types.Float)(&r.PsFluxSigma)
		
	
	case 1:
		
		
			return (*types.Float)(&r.PsRaSigma)
		
	
	case 2:
		
		
			return (*types.Float)(&r.PsDeclSigma)
		
	
	case 3:
		
		
			return (*types.Float)(&r.PsFlux_psRa_Cov)
		
	
	case 4:
		
		
			return (*types.Float)(&r.PsFlux_psDecl_Cov)
		
	
	case 5:
		
		
			return (*types.Float)(&r.PsRa_psDecl_Cov)
		
	
	}
	panic("Unknown field index")
}

func (r *Ps_Cov) SetDefault(i int) {
	switch (i) {
	
        
	
        
	
        
	
        
	
        
	
        
	
	}
	panic("Unknown field index")
}

func (_ *Ps_Cov) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Ps_Cov) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Ps_Cov) Finalize() { }


func (_ *Ps_Cov) AvroCRC64Fingerprint() []byte {
  return []byte(Ps_CovAvroCRC64Fingerprint)
}
