// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"github.com/actgardner/gogen-avro/vm/types"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/compiler"
)


type Ra_decl_Cov struct {

	
	
		RaSigma float32
	

	
	
		DeclSigma float32
	

	
	
		Ra_decl_Cov float32
	

}

const Ra_decl_CovAvroCRC64Fingerprint = "\xf4\t\x91\xd3\xe1\xf4,\xbf"

func NewRa_decl_Cov() (*Ra_decl_Cov) {
	return &Ra_decl_Cov{}
}

func DeserializeRa_decl_Cov(r io.Reader) (*Ra_decl_Cov, error) {
	t := NewRa_decl_Cov()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err
	}
	return t, err
}

func DeserializeRa_decl_CovFromSchema(r io.Reader, schema string) (*Ra_decl_Cov, error) {
	t := NewRa_decl_Cov()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err
	}
	return t, err
}

func writeRa_decl_Cov(r *Ra_decl_Cov, w io.Writer) error {
	var err error
	
	err = vm.WriteFloat( r.RaSigma, w)
	if err != nil {
		return err
	}
	
	err = vm.WriteFloat( r.DeclSigma, w)
	if err != nil {
		return err
	}
	
	err = vm.WriteFloat( r.Ra_decl_Cov, w)
	if err != nil {
		return err
	}
	
	return err
}

func (r *Ra_decl_Cov) Serialize(w io.Writer) error {
	return writeRa_decl_Cov(r, w)
}

func (r *Ra_decl_Cov) Schema() string {
	return "{\"fields\":[{\"name\":\"raSigma\",\"type\":\"float\"},{\"name\":\"declSigma\",\"type\":\"float\"},{\"name\":\"ra_decl_Cov\",\"type\":\"float\"}],\"name\":\"lsst.ra_decl_Cov\",\"type\":\"record\"}"
}

func (r *Ra_decl_Cov) SchemaName() string {
	return "lsst.ra_decl_Cov"
}

func (_ *Ra_decl_Cov) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Ra_decl_Cov) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Ra_decl_Cov) SetLong(v int64) { panic("Unsupported operation") }
func (_ *Ra_decl_Cov) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Ra_decl_Cov) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Ra_decl_Cov) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Ra_decl_Cov) SetString(v string) { panic("Unsupported operation") }
func (_ *Ra_decl_Cov) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *Ra_decl_Cov) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
			return (*types.Float)(&r.RaSigma)
		
	
	case 1:
		
		
			return (*types.Float)(&r.DeclSigma)
		
	
	case 2:
		
		
			return (*types.Float)(&r.Ra_decl_Cov)
		
	
	}
	panic("Unknown field index")
}

func (r *Ra_decl_Cov) SetDefault(i int) {
	switch (i) {
	
        
	
        
	
        
	
	}
	panic("Unknown field index")
}

func (_ *Ra_decl_Cov) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Ra_decl_Cov) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Ra_decl_Cov) Finalize() { }


func (_ *Ra_decl_Cov) AvroCRC64Fingerprint() []byte {
  return []byte(Ra_decl_CovAvroCRC64Fingerprint)
}
