// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullFloatTypeEnum int
const (

	 UnionNullFloatTypeEnumNull UnionNullFloatTypeEnum = 0

	 UnionNullFloatTypeEnumFloat UnionNullFloatTypeEnum = 1

)

type UnionNullFloat struct {

	Null *types.NullVal

	Float float32

	UnionType UnionNullFloatTypeEnum
}

func writeUnionNullFloat(r *UnionNullFloat, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullFloatTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullFloatTypeEnumFloat:
		return vm.WriteFloat(r.Float, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullFloat")
}

func NewUnionNullFloat() *UnionNullFloat {
	return &UnionNullFloat{}
}

func (_ *UnionNullFloat) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullFloat) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullFloat) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullFloat) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullFloat) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullFloat) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullFloat) SetLong(v int64) { 
	r.UnionType = (UnionNullFloatTypeEnum)(v)
}
func (r *UnionNullFloat) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.Float)(&r.Float)
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullFloat) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullFloat) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullFloat) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullFloat) Finalize()  { }
