// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullArrayDiaNondetectionLimitTypeEnum int
const (

	 UnionNullArrayDiaNondetectionLimitTypeEnumNull UnionNullArrayDiaNondetectionLimitTypeEnum = 0

	 UnionNullArrayDiaNondetectionLimitTypeEnumArrayDiaNondetectionLimit UnionNullArrayDiaNondetectionLimitTypeEnum = 1

)

type UnionNullArrayDiaNondetectionLimit struct {

	Null *types.NullVal

	ArrayDiaNondetectionLimit []*DiaNondetectionLimit

	UnionType UnionNullArrayDiaNondetectionLimitTypeEnum
}

func writeUnionNullArrayDiaNondetectionLimit(r *UnionNullArrayDiaNondetectionLimit, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullArrayDiaNondetectionLimitTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullArrayDiaNondetectionLimitTypeEnumArrayDiaNondetectionLimit:
		return writeArrayDiaNondetectionLimit(r.ArrayDiaNondetectionLimit, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullArrayDiaNondetectionLimit")
}

func NewUnionNullArrayDiaNondetectionLimit() *UnionNullArrayDiaNondetectionLimit {
	return &UnionNullArrayDiaNondetectionLimit{}
}

func (_ *UnionNullArrayDiaNondetectionLimit) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullArrayDiaNondetectionLimit) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullArrayDiaNondetectionLimit) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullArrayDiaNondetectionLimit) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullArrayDiaNondetectionLimit) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullArrayDiaNondetectionLimit) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullArrayDiaNondetectionLimit) SetLong(v int64) { 
	r.UnionType = (UnionNullArrayDiaNondetectionLimitTypeEnum)(v)
}
func (r *UnionNullArrayDiaNondetectionLimit) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.ArrayDiaNondetectionLimit = make([]*DiaNondetectionLimit, 0)
		
		
		return (*ArrayDiaNondetectionLimitWrapper)(&r.ArrayDiaNondetectionLimit)
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullArrayDiaNondetectionLimit) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullArrayDiaNondetectionLimit) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullArrayDiaNondetectionLimit) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullArrayDiaNondetectionLimit) Finalize()  { }
