// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullYLcPeriodicTypeEnum int
const (

	 UnionNullYLcPeriodicTypeEnumNull UnionNullYLcPeriodicTypeEnum = 0

	 UnionNullYLcPeriodicTypeEnumYLcPeriodic UnionNullYLcPeriodicTypeEnum = 1

)

type UnionNullYLcPeriodic struct {

	Null *types.NullVal

	YLcPeriodic *YLcPeriodic

	UnionType UnionNullYLcPeriodicTypeEnum
}

func writeUnionNullYLcPeriodic(r *UnionNullYLcPeriodic, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullYLcPeriodicTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullYLcPeriodicTypeEnumYLcPeriodic:
		return writeYLcPeriodic(r.YLcPeriodic, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullYLcPeriodic")
}

func NewUnionNullYLcPeriodic() *UnionNullYLcPeriodic {
	return &UnionNullYLcPeriodic{}
}

func (_ *UnionNullYLcPeriodic) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullYLcPeriodic) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullYLcPeriodic) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullYLcPeriodic) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullYLcPeriodic) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullYLcPeriodic) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullYLcPeriodic) SetLong(v int64) { 
	r.UnionType = (UnionNullYLcPeriodicTypeEnum)(v)
}
func (r *UnionNullYLcPeriodic) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.YLcPeriodic = NewYLcPeriodic()
		
		
		return r.YLcPeriodic
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullYLcPeriodic) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullYLcPeriodic) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullYLcPeriodic) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullYLcPeriodic) Finalize()  { }
