// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullPs_CovTypeEnum int
const (

	 UnionNullPs_CovTypeEnumNull UnionNullPs_CovTypeEnum = 0

	 UnionNullPs_CovTypeEnumPs_Cov UnionNullPs_CovTypeEnum = 1

)

type UnionNullPs_Cov struct {

	Null *types.NullVal

	Ps_Cov *Ps_Cov

	UnionType UnionNullPs_CovTypeEnum
}

func writeUnionNullPs_Cov(r *UnionNullPs_Cov, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullPs_CovTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullPs_CovTypeEnumPs_Cov:
		return writePs_Cov(r.Ps_Cov, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullPs_Cov")
}

func NewUnionNullPs_Cov() *UnionNullPs_Cov {
	return &UnionNullPs_Cov{}
}

func (_ *UnionNullPs_Cov) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullPs_Cov) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullPs_Cov) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullPs_Cov) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullPs_Cov) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullPs_Cov) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullPs_Cov) SetLong(v int64) { 
	r.UnionType = (UnionNullPs_CovTypeEnum)(v)
}
func (r *UnionNullPs_Cov) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.Ps_Cov = NewPs_Cov()
		
		
		return r.Ps_Cov
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullPs_Cov) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullPs_Cov) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullPs_Cov) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullPs_Cov) Finalize()  { }
