// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullZLcPeriodicTypeEnum int
const (

	 UnionNullZLcPeriodicTypeEnumNull UnionNullZLcPeriodicTypeEnum = 0

	 UnionNullZLcPeriodicTypeEnumZLcPeriodic UnionNullZLcPeriodicTypeEnum = 1

)

type UnionNullZLcPeriodic struct {

	Null *types.NullVal

	ZLcPeriodic *ZLcPeriodic

	UnionType UnionNullZLcPeriodicTypeEnum
}

func writeUnionNullZLcPeriodic(r *UnionNullZLcPeriodic, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullZLcPeriodicTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullZLcPeriodicTypeEnumZLcPeriodic:
		return writeZLcPeriodic(r.ZLcPeriodic, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullZLcPeriodic")
}

func NewUnionNullZLcPeriodic() *UnionNullZLcPeriodic {
	return &UnionNullZLcPeriodic{}
}

func (_ *UnionNullZLcPeriodic) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullZLcPeriodic) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullZLcPeriodic) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullZLcPeriodic) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullZLcPeriodic) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullZLcPeriodic) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullZLcPeriodic) SetLong(v int64) { 
	r.UnionType = (UnionNullZLcPeriodicTypeEnum)(v)
}
func (r *UnionNullZLcPeriodic) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.ZLcPeriodic = NewZLcPeriodic()
		
		
		return r.ZLcPeriodic
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullZLcPeriodic) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullZLcPeriodic) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullZLcPeriodic) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullZLcPeriodic) Finalize()  { }
