// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullULcPeriodicTypeEnum int
const (

	 UnionNullULcPeriodicTypeEnumNull UnionNullULcPeriodicTypeEnum = 0

	 UnionNullULcPeriodicTypeEnumULcPeriodic UnionNullULcPeriodicTypeEnum = 1

)

type UnionNullULcPeriodic struct {

	Null *types.NullVal

	ULcPeriodic *ULcPeriodic

	UnionType UnionNullULcPeriodicTypeEnum
}

func writeUnionNullULcPeriodic(r *UnionNullULcPeriodic, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullULcPeriodicTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullULcPeriodicTypeEnumULcPeriodic:
		return writeULcPeriodic(r.ULcPeriodic, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullULcPeriodic")
}

func NewUnionNullULcPeriodic() *UnionNullULcPeriodic {
	return &UnionNullULcPeriodic{}
}

func (_ *UnionNullULcPeriodic) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullULcPeriodic) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullULcPeriodic) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullULcPeriodic) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullULcPeriodic) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullULcPeriodic) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullULcPeriodic) SetLong(v int64) { 
	r.UnionType = (UnionNullULcPeriodicTypeEnum)(v)
}
func (r *UnionNullULcPeriodic) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.ULcPeriodic = NewULcPeriodic()
		
		
		return r.ULcPeriodic
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullULcPeriodic) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullULcPeriodic) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullULcPeriodic) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullULcPeriodic) Finalize()  { }
