// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullSsObjectTypeEnum int
const (

	 UnionNullSsObjectTypeEnumNull UnionNullSsObjectTypeEnum = 0

	 UnionNullSsObjectTypeEnumSsObject UnionNullSsObjectTypeEnum = 1

)

type UnionNullSsObject struct {

	Null *types.NullVal

	SsObject *SsObject

	UnionType UnionNullSsObjectTypeEnum
}

func writeUnionNullSsObject(r *UnionNullSsObject, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullSsObjectTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullSsObjectTypeEnumSsObject:
		return writeSsObject(r.SsObject, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullSsObject")
}

func NewUnionNullSsObject() *UnionNullSsObject {
	return &UnionNullSsObject{}
}

func (_ *UnionNullSsObject) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullSsObject) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullSsObject) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullSsObject) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullSsObject) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullSsObject) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullSsObject) SetLong(v int64) { 
	r.UnionType = (UnionNullSsObjectTypeEnum)(v)
}
func (r *UnionNullSsObject) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.SsObject = NewSsObject()
		
		
		return r.SsObject
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullSsObject) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullSsObject) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullSsObject) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullSsObject) Finalize()  { }
