// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullDiaObjectTypeEnum int
const (

	 UnionNullDiaObjectTypeEnumNull UnionNullDiaObjectTypeEnum = 0

	 UnionNullDiaObjectTypeEnumDiaObject UnionNullDiaObjectTypeEnum = 1

)

type UnionNullDiaObject struct {

	Null *types.NullVal

	DiaObject *DiaObject

	UnionType UnionNullDiaObjectTypeEnum
}

func writeUnionNullDiaObject(r *UnionNullDiaObject, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullDiaObjectTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullDiaObjectTypeEnumDiaObject:
		return writeDiaObject(r.DiaObject, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullDiaObject")
}

func NewUnionNullDiaObject() *UnionNullDiaObject {
	return &UnionNullDiaObject{}
}

func (_ *UnionNullDiaObject) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullDiaObject) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullDiaObject) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullDiaObject) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullDiaObject) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullDiaObject) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullDiaObject) SetLong(v int64) { 
	r.UnionType = (UnionNullDiaObjectTypeEnum)(v)
}
func (r *UnionNullDiaObject) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.DiaObject = NewDiaObject()
		
		
		return r.DiaObject
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullDiaObject) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullDiaObject) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullDiaObject) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullDiaObject) Finalize()  { }
