// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullArrayDiaForcedSourceTypeEnum int
const (

	 UnionNullArrayDiaForcedSourceTypeEnumNull UnionNullArrayDiaForcedSourceTypeEnum = 0

	 UnionNullArrayDiaForcedSourceTypeEnumArrayDiaForcedSource UnionNullArrayDiaForcedSourceTypeEnum = 1

)

type UnionNullArrayDiaForcedSource struct {

	Null *types.NullVal

	ArrayDiaForcedSource []*DiaForcedSource

	UnionType UnionNullArrayDiaForcedSourceTypeEnum
}

func writeUnionNullArrayDiaForcedSource(r *UnionNullArrayDiaForcedSource, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullArrayDiaForcedSourceTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullArrayDiaForcedSourceTypeEnumArrayDiaForcedSource:
		return writeArrayDiaForcedSource(r.ArrayDiaForcedSource, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullArrayDiaForcedSource")
}

func NewUnionNullArrayDiaForcedSource() *UnionNullArrayDiaForcedSource {
	return &UnionNullArrayDiaForcedSource{}
}

func (_ *UnionNullArrayDiaForcedSource) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullArrayDiaForcedSource) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullArrayDiaForcedSource) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullArrayDiaForcedSource) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullArrayDiaForcedSource) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullArrayDiaForcedSource) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullArrayDiaForcedSource) SetLong(v int64) { 
	r.UnionType = (UnionNullArrayDiaForcedSourceTypeEnum)(v)
}
func (r *UnionNullArrayDiaForcedSource) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.ArrayDiaForcedSource = make([]*DiaForcedSource, 0)
		
		
		return (*ArrayDiaForcedSourceWrapper)(&r.ArrayDiaForcedSource)
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullArrayDiaForcedSource) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullArrayDiaForcedSource) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullArrayDiaForcedSource) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullArrayDiaForcedSource) Finalize()  { }
