// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullOeTypeEnum int
const (

	 UnionNullOeTypeEnumNull UnionNullOeTypeEnum = 0

	 UnionNullOeTypeEnumOe UnionNullOeTypeEnum = 1

)

type UnionNullOe struct {

	Null *types.NullVal

	Oe *Oe

	UnionType UnionNullOeTypeEnum
}

func writeUnionNullOe(r *UnionNullOe, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullOeTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullOeTypeEnumOe:
		return writeOe(r.Oe, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullOe")
}

func NewUnionNullOe() *UnionNullOe {
	return &UnionNullOe{}
}

func (_ *UnionNullOe) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullOe) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullOe) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullOe) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullOe) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullOe) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullOe) SetLong(v int64) { 
	r.UnionType = (UnionNullOeTypeEnum)(v)
}
func (r *UnionNullOe) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.Oe = NewOe()
		
		
		return r.Oe
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullOe) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullOe) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullOe) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullOe) Finalize()  { }
