// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullI_covTypeEnum int
const (

	 UnionNullI_covTypeEnumNull UnionNullI_covTypeEnum = 0

	 UnionNullI_covTypeEnumI_cov UnionNullI_covTypeEnum = 1

)

type UnionNullI_cov struct {

	Null *types.NullVal

	I_cov *I_cov

	UnionType UnionNullI_covTypeEnum
}

func writeUnionNullI_cov(r *UnionNullI_cov, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullI_covTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullI_covTypeEnumI_cov:
		return writeI_cov(r.I_cov, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullI_cov")
}

func NewUnionNullI_cov() *UnionNullI_cov {
	return &UnionNullI_cov{}
}

func (_ *UnionNullI_cov) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullI_cov) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullI_cov) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullI_cov) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullI_cov) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullI_cov) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullI_cov) SetLong(v int64) { 
	r.UnionType = (UnionNullI_covTypeEnum)(v)
}
func (r *UnionNullI_cov) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.I_cov = NewI_cov()
		
		
		return r.I_cov
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullI_cov) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullI_cov) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullI_cov) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullI_cov) Finalize()  { }
