// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullZLcNonPeriodicTypeEnum int
const (

	 UnionNullZLcNonPeriodicTypeEnumNull UnionNullZLcNonPeriodicTypeEnum = 0

	 UnionNullZLcNonPeriodicTypeEnumZLcNonPeriodic UnionNullZLcNonPeriodicTypeEnum = 1

)

type UnionNullZLcNonPeriodic struct {

	Null *types.NullVal

	ZLcNonPeriodic *ZLcNonPeriodic

	UnionType UnionNullZLcNonPeriodicTypeEnum
}

func writeUnionNullZLcNonPeriodic(r *UnionNullZLcNonPeriodic, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullZLcNonPeriodicTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullZLcNonPeriodicTypeEnumZLcNonPeriodic:
		return writeZLcNonPeriodic(r.ZLcNonPeriodic, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullZLcNonPeriodic")
}

func NewUnionNullZLcNonPeriodic() *UnionNullZLcNonPeriodic {
	return &UnionNullZLcNonPeriodic{}
}

func (_ *UnionNullZLcNonPeriodic) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullZLcNonPeriodic) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullZLcNonPeriodic) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullZLcNonPeriodic) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullZLcNonPeriodic) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullZLcNonPeriodic) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullZLcNonPeriodic) SetLong(v int64) { 
	r.UnionType = (UnionNullZLcNonPeriodicTypeEnum)(v)
}
func (r *UnionNullZLcNonPeriodic) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.ZLcNonPeriodic = NewZLcNonPeriodic()
		
		
		return r.ZLcNonPeriodic
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullZLcNonPeriodic) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullZLcNonPeriodic) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullZLcNonPeriodic) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullZLcNonPeriodic) Finalize()  { }
