// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullTrail_CovTypeEnum int
const (

	 UnionNullTrail_CovTypeEnumNull UnionNullTrail_CovTypeEnum = 0

	 UnionNullTrail_CovTypeEnumTrail_Cov UnionNullTrail_CovTypeEnum = 1

)

type UnionNullTrail_Cov struct {

	Null *types.NullVal

	Trail_Cov *Trail_Cov

	UnionType UnionNullTrail_CovTypeEnum
}

func writeUnionNullTrail_Cov(r *UnionNullTrail_Cov, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullTrail_CovTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullTrail_CovTypeEnumTrail_Cov:
		return writeTrail_Cov(r.Trail_Cov, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullTrail_Cov")
}

func NewUnionNullTrail_Cov() *UnionNullTrail_Cov {
	return &UnionNullTrail_Cov{}
}

func (_ *UnionNullTrail_Cov) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullTrail_Cov) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullTrail_Cov) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullTrail_Cov) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullTrail_Cov) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullTrail_Cov) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullTrail_Cov) SetLong(v int64) { 
	r.UnionType = (UnionNullTrail_CovTypeEnum)(v)
}
func (r *UnionNullTrail_Cov) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.Trail_Cov = NewTrail_Cov()
		
		
		return r.Trail_Cov
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullTrail_Cov) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullTrail_Cov) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullTrail_Cov) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullTrail_Cov) Finalize()  { }
