// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullYLcNonPeriodicTypeEnum int
const (

	 UnionNullYLcNonPeriodicTypeEnumNull UnionNullYLcNonPeriodicTypeEnum = 0

	 UnionNullYLcNonPeriodicTypeEnumYLcNonPeriodic UnionNullYLcNonPeriodicTypeEnum = 1

)

type UnionNullYLcNonPeriodic struct {

	Null *types.NullVal

	YLcNonPeriodic *YLcNonPeriodic

	UnionType UnionNullYLcNonPeriodicTypeEnum
}

func writeUnionNullYLcNonPeriodic(r *UnionNullYLcNonPeriodic, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullYLcNonPeriodicTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullYLcNonPeriodicTypeEnumYLcNonPeriodic:
		return writeYLcNonPeriodic(r.YLcNonPeriodic, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullYLcNonPeriodic")
}

func NewUnionNullYLcNonPeriodic() *UnionNullYLcNonPeriodic {
	return &UnionNullYLcNonPeriodic{}
}

func (_ *UnionNullYLcNonPeriodic) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullYLcNonPeriodic) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullYLcNonPeriodic) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullYLcNonPeriodic) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullYLcNonPeriodic) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullYLcNonPeriodic) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullYLcNonPeriodic) SetLong(v int64) { 
	r.UnionType = (UnionNullYLcNonPeriodicTypeEnum)(v)
}
func (r *UnionNullYLcNonPeriodic) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.YLcNonPeriodic = NewYLcNonPeriodic()
		
		
		return r.YLcNonPeriodic
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullYLcNonPeriodic) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullYLcNonPeriodic) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullYLcNonPeriodic) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullYLcNonPeriodic) Finalize()  { }
