// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullGLcPeriodicTypeEnum int
const (

	 UnionNullGLcPeriodicTypeEnumNull UnionNullGLcPeriodicTypeEnum = 0

	 UnionNullGLcPeriodicTypeEnumGLcPeriodic UnionNullGLcPeriodicTypeEnum = 1

)

type UnionNullGLcPeriodic struct {

	Null *types.NullVal

	GLcPeriodic *GLcPeriodic

	UnionType UnionNullGLcPeriodicTypeEnum
}

func writeUnionNullGLcPeriodic(r *UnionNullGLcPeriodic, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullGLcPeriodicTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullGLcPeriodicTypeEnumGLcPeriodic:
		return writeGLcPeriodic(r.GLcPeriodic, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullGLcPeriodic")
}

func NewUnionNullGLcPeriodic() *UnionNullGLcPeriodic {
	return &UnionNullGLcPeriodic{}
}

func (_ *UnionNullGLcPeriodic) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullGLcPeriodic) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullGLcPeriodic) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullGLcPeriodic) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullGLcPeriodic) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullGLcPeriodic) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullGLcPeriodic) SetLong(v int64) { 
	r.UnionType = (UnionNullGLcPeriodicTypeEnum)(v)
}
func (r *UnionNullGLcPeriodic) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.GLcPeriodic = NewGLcPeriodic()
		
		
		return r.GLcPeriodic
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullGLcPeriodic) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullGLcPeriodic) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullGLcPeriodic) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullGLcPeriodic) Finalize()  { }
