// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullRa_decl_CovTypeEnum int
const (

	 UnionNullRa_decl_CovTypeEnumNull UnionNullRa_decl_CovTypeEnum = 0

	 UnionNullRa_decl_CovTypeEnumRa_decl_Cov UnionNullRa_decl_CovTypeEnum = 1

)

type UnionNullRa_decl_Cov struct {

	Null *types.NullVal

	Ra_decl_Cov *Ra_decl_Cov

	UnionType UnionNullRa_decl_CovTypeEnum
}

func writeUnionNullRa_decl_Cov(r *UnionNullRa_decl_Cov, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullRa_decl_CovTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullRa_decl_CovTypeEnumRa_decl_Cov:
		return writeRa_decl_Cov(r.Ra_decl_Cov, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullRa_decl_Cov")
}

func NewUnionNullRa_decl_Cov() *UnionNullRa_decl_Cov {
	return &UnionNullRa_decl_Cov{}
}

func (_ *UnionNullRa_decl_Cov) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullRa_decl_Cov) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullRa_decl_Cov) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullRa_decl_Cov) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullRa_decl_Cov) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullRa_decl_Cov) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullRa_decl_Cov) SetLong(v int64) { 
	r.UnionType = (UnionNullRa_decl_CovTypeEnum)(v)
}
func (r *UnionNullRa_decl_Cov) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.Ra_decl_Cov = NewRa_decl_Cov()
		
		
		return r.Ra_decl_Cov
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullRa_decl_Cov) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullRa_decl_Cov) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullRa_decl_Cov) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullRa_decl_Cov) Finalize()  { }
