// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullULcNonPeriodicTypeEnum int
const (

	 UnionNullULcNonPeriodicTypeEnumNull UnionNullULcNonPeriodicTypeEnum = 0

	 UnionNullULcNonPeriodicTypeEnumULcNonPeriodic UnionNullULcNonPeriodicTypeEnum = 1

)

type UnionNullULcNonPeriodic struct {

	Null *types.NullVal

	ULcNonPeriodic *ULcNonPeriodic

	UnionType UnionNullULcNonPeriodicTypeEnum
}

func writeUnionNullULcNonPeriodic(r *UnionNullULcNonPeriodic, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullULcNonPeriodicTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullULcNonPeriodicTypeEnumULcNonPeriodic:
		return writeULcNonPeriodic(r.ULcNonPeriodic, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullULcNonPeriodic")
}

func NewUnionNullULcNonPeriodic() *UnionNullULcNonPeriodic {
	return &UnionNullULcNonPeriodic{}
}

func (_ *UnionNullULcNonPeriodic) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullULcNonPeriodic) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullULcNonPeriodic) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullULcNonPeriodic) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullULcNonPeriodic) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullULcNonPeriodic) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullULcNonPeriodic) SetLong(v int64) { 
	r.UnionType = (UnionNullULcNonPeriodicTypeEnum)(v)
}
func (r *UnionNullULcNonPeriodic) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.ULcNonPeriodic = NewULcNonPeriodic()
		
		
		return r.ULcNonPeriodic
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullULcNonPeriodic) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullULcNonPeriodic) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullULcNonPeriodic) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullULcNonPeriodic) Finalize()  { }
