// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullRLcPeriodicTypeEnum int
const (

	 UnionNullRLcPeriodicTypeEnumNull UnionNullRLcPeriodicTypeEnum = 0

	 UnionNullRLcPeriodicTypeEnumRLcPeriodic UnionNullRLcPeriodicTypeEnum = 1

)

type UnionNullRLcPeriodic struct {

	Null *types.NullVal

	RLcPeriodic *RLcPeriodic

	UnionType UnionNullRLcPeriodicTypeEnum
}

func writeUnionNullRLcPeriodic(r *UnionNullRLcPeriodic, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullRLcPeriodicTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullRLcPeriodicTypeEnumRLcPeriodic:
		return writeRLcPeriodic(r.RLcPeriodic, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullRLcPeriodic")
}

func NewUnionNullRLcPeriodic() *UnionNullRLcPeriodic {
	return &UnionNullRLcPeriodic{}
}

func (_ *UnionNullRLcPeriodic) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullRLcPeriodic) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullRLcPeriodic) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullRLcPeriodic) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullRLcPeriodic) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullRLcPeriodic) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullRLcPeriodic) SetLong(v int64) { 
	r.UnionType = (UnionNullRLcPeriodicTypeEnum)(v)
}
func (r *UnionNullRLcPeriodic) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.RLcPeriodic = NewRLcPeriodic()
		
		
		return r.RLcPeriodic
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullRLcPeriodic) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullRLcPeriodic) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullRLcPeriodic) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullRLcPeriodic) Finalize()  { }
