// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullILcNonPeriodicTypeEnum int
const (

	 UnionNullILcNonPeriodicTypeEnumNull UnionNullILcNonPeriodicTypeEnum = 0

	 UnionNullILcNonPeriodicTypeEnumILcNonPeriodic UnionNullILcNonPeriodicTypeEnum = 1

)

type UnionNullILcNonPeriodic struct {

	Null *types.NullVal

	ILcNonPeriodic *ILcNonPeriodic

	UnionType UnionNullILcNonPeriodicTypeEnum
}

func writeUnionNullILcNonPeriodic(r *UnionNullILcNonPeriodic, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullILcNonPeriodicTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullILcNonPeriodicTypeEnumILcNonPeriodic:
		return writeILcNonPeriodic(r.ILcNonPeriodic, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullILcNonPeriodic")
}

func NewUnionNullILcNonPeriodic() *UnionNullILcNonPeriodic {
	return &UnionNullILcNonPeriodic{}
}

func (_ *UnionNullILcNonPeriodic) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullILcNonPeriodic) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullILcNonPeriodic) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullILcNonPeriodic) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullILcNonPeriodic) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullILcNonPeriodic) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullILcNonPeriodic) SetLong(v int64) { 
	r.UnionType = (UnionNullILcNonPeriodicTypeEnum)(v)
}
func (r *UnionNullILcNonPeriodic) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.ILcNonPeriodic = NewILcNonPeriodic()
		
		
		return r.ILcNonPeriodic
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullILcNonPeriodic) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullILcNonPeriodic) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullILcNonPeriodic) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullILcNonPeriodic) Finalize()  { }
