// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullLongTypeEnum int
const (

	 UnionNullLongTypeEnumNull UnionNullLongTypeEnum = 0

	 UnionNullLongTypeEnumLong UnionNullLongTypeEnum = 1

)

type UnionNullLong struct {

	Null *types.NullVal

	Long int64

	UnionType UnionNullLongTypeEnum
}

func writeUnionNullLong(r *UnionNullLong, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullLongTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullLongTypeEnumLong:
		return vm.WriteLong(r.Long, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullLong")
}

func NewUnionNullLong() *UnionNullLong {
	return &UnionNullLong{}
}

func (_ *UnionNullLong) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullLong) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullLong) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullLong) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullLong) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullLong) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullLong) SetLong(v int64) { 
	r.UnionType = (UnionNullLongTypeEnum)(v)
}
func (r *UnionNullLong) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.Long)(&r.Long)
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullLong) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullLong) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullLong) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullLong) Finalize()  { }
