// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullOe_CovTypeEnum int
const (

	 UnionNullOe_CovTypeEnumNull UnionNullOe_CovTypeEnum = 0

	 UnionNullOe_CovTypeEnumOe_Cov UnionNullOe_CovTypeEnum = 1

)

type UnionNullOe_Cov struct {

	Null *types.NullVal

	Oe_Cov *Oe_Cov

	UnionType UnionNullOe_CovTypeEnum
}

func writeUnionNullOe_Cov(r *UnionNullOe_Cov, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullOe_CovTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullOe_CovTypeEnumOe_Cov:
		return writeOe_Cov(r.Oe_Cov, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullOe_Cov")
}

func NewUnionNullOe_Cov() *UnionNullOe_Cov {
	return &UnionNullOe_Cov{}
}

func (_ *UnionNullOe_Cov) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullOe_Cov) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullOe_Cov) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullOe_Cov) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullOe_Cov) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullOe_Cov) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullOe_Cov) SetLong(v int64) { 
	r.UnionType = (UnionNullOe_CovTypeEnum)(v)
}
func (r *UnionNullOe_Cov) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.Oe_Cov = NewOe_Cov()
		
		
		return r.Oe_Cov
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullOe_Cov) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullOe_Cov) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullOe_Cov) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullOe_Cov) Finalize()  { }
