// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullRLcNonPeriodicTypeEnum int
const (

	 UnionNullRLcNonPeriodicTypeEnumNull UnionNullRLcNonPeriodicTypeEnum = 0

	 UnionNullRLcNonPeriodicTypeEnumRLcNonPeriodic UnionNullRLcNonPeriodicTypeEnum = 1

)

type UnionNullRLcNonPeriodic struct {

	Null *types.NullVal

	RLcNonPeriodic *RLcNonPeriodic

	UnionType UnionNullRLcNonPeriodicTypeEnum
}

func writeUnionNullRLcNonPeriodic(r *UnionNullRLcNonPeriodic, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullRLcNonPeriodicTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullRLcNonPeriodicTypeEnumRLcNonPeriodic:
		return writeRLcNonPeriodic(r.RLcNonPeriodic, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullRLcNonPeriodic")
}

func NewUnionNullRLcNonPeriodic() *UnionNullRLcNonPeriodic {
	return &UnionNullRLcNonPeriodic{}
}

func (_ *UnionNullRLcNonPeriodic) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullRLcNonPeriodic) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullRLcNonPeriodic) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullRLcNonPeriodic) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullRLcNonPeriodic) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullRLcNonPeriodic) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullRLcNonPeriodic) SetLong(v int64) { 
	r.UnionType = (UnionNullRLcNonPeriodicTypeEnum)(v)
}
func (r *UnionNullRLcNonPeriodic) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.RLcNonPeriodic = NewRLcNonPeriodic()
		
		
		return r.RLcNonPeriodic
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullRLcNonPeriodic) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullRLcNonPeriodic) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullRLcNonPeriodic) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullRLcNonPeriodic) Finalize()  { }
