// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     lsst.alert.avsc
 *     lsst.alert.cutout.avsc
 *     lsst.alert.diaForcedSource.avsc
 *     lsst.alert.diaNondetectionLimit.avsc
 *     lsst.alert.diaSource.avsc
 *     lsst.diaObject.avsc
 *     lsst.ssObject.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullX_y_CovTypeEnum int
const (

	 UnionNullX_y_CovTypeEnumNull UnionNullX_y_CovTypeEnum = 0

	 UnionNullX_y_CovTypeEnumX_y_Cov UnionNullX_y_CovTypeEnum = 1

)

type UnionNullX_y_Cov struct {

	Null *types.NullVal

	X_y_Cov *X_y_Cov

	UnionType UnionNullX_y_CovTypeEnum
}

func writeUnionNullX_y_Cov(r *UnionNullX_y_Cov, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullX_y_CovTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullX_y_CovTypeEnumX_y_Cov:
		return writeX_y_Cov(r.X_y_Cov, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullX_y_Cov")
}

func NewUnionNullX_y_Cov() *UnionNullX_y_Cov {
	return &UnionNullX_y_Cov{}
}

func (_ *UnionNullX_y_Cov) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullX_y_Cov) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullX_y_Cov) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullX_y_Cov) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullX_y_Cov) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullX_y_Cov) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullX_y_Cov) SetLong(v int64) { 
	r.UnionType = (UnionNullX_y_CovTypeEnum)(v)
}
func (r *UnionNullX_y_Cov) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.X_y_Cov = NewX_y_Cov()
		
		
		return r.X_y_Cov
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullX_y_Cov) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullX_y_Cov) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullX_y_Cov) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullX_y_Cov) Finalize()  { }
